const express = require('express');
const controller = require('../controllers/authController');
const { protect } = require('../middleware/auth');
const router = express.Router();
router.post('/register', controller.register);
router.post('/login', controller.login);
router.get('/me', protect, controller.getme);
router.post('/forgotpassword', controller.forgotPassword);
router.post('/resetPassword/:resettoken', controller.resetPassword);
router.post('/updateUserInfo', protect, controller.updateUserDetails);
router.post('/updateUserPassword', protect, controller.updateUserPassword);
module.exports = router;
